db:
  image: postgres
  container_name: postgres
  environment:
      - POSTGRES_PASSWORD=pass
  restart: unless-stopped
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  ports:
    - "5432:5432"    